name: 'build'

on:
  workflow_dispatch:
  push:
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: 'Setup Rust'
      if: matrix.platform.rust_target == 'aarch64-apple-darwin'
      run: rustup target add aarch64-apple-darwin

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.platform.rust_target }}
        workspaces: |
          src-tauri

    - name: install dependencies (ubuntu only)
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libasound2-dev

    - name: install npm packages
      run: npm ci

    - uses: JonasKruckenberg/tauri-build@v1.3.0
      id: tauri_build
      with:
        target: ${{ matrix.platform.rust_target }}

    # The artifacts output can now be used to upload the artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: build ${{ matrix.platform.os }} ${{ matrix.platform.rust_target }}
        path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
